---
title: A title
subtitle: A subtitle
format: ucdavis-revealjs
author:
  - name: Your Name
    orcid: 0000-0000-0000-0000
    email: alias@email.com
    affiliations: UC Davis
date: last-modified
---

## Example slide

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

## Additional theme classes

### Some extra things you can do with the ucdavis theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #022851"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #FFBF00"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Want more?

### Based on quarto-revealjs-clean

This theme is a UC Davis-branded fork of Grant McDermott's
[clean theme](https://github.com/grantmcdermott/quarto-revealjs-clean).

Add the theme to an existing project:

```{.bash}
quarto install extension hail2thief/quarto-revealjs-ucdavis
```

... or, create a new project using this slide deck as a template:

```{.bash}
quarto use template hail2thief/quarto-revealjs-ucdavis
```

## Summary {#sec-summary}

### A UC Davis presentation theme

The Quarto reveal.js UC Davis theme uses Public Sans and UC Davis brand colors
(Aggie Blue `#022851` and Aggie Gold `#B3A369`) for a clean, professional look.
